{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.swallow.documentation.FoundationX\/s5ErrorP","doc:\/\/com.swallow.documentation.FoundationX\/s8SendableP"],"type":"inheritsFrom","title":"Inherits From"}],"variants":[{"paths":["\/documentation\/foundationx\/recoverableerror"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX"]]},"sections":[],"abstract":[{"text":"Describes an error that may be recoverable by presenting several","type":"text"},{"type":"text","text":" "},{"text":"potential recovery options to the user.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RecoverableError"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}]}],"kind":"declarations"}],"metadata":{"externalID":"s:10Foundation16RecoverableErrorP","modules":[{"name":"FoundationX"}],"platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"name":"macOS","introducedAt":"10.10","beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","beta":false,"unavailable":false},{"unavailable":false,"introducedAt":"2.0","name":"watchOS","deprecated":false,"beta":false}],"role":"symbol","roleHeading":"Protocol","title":"RecoverableError","navigatorTitle":[{"kind":"identifier","text":"RecoverableError"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RecoverableError"}],"symbolKind":"protocol"},"kind":"symbol","topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/recoveryOptions"],"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/attemptRecovery(optionIndex:)","doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/attemptRecovery(optionIndex:resultHandler:)-5rlzq"],"title":"Instance Methods","generated":true}],"references":{"doc://com.swallow.documentation.FoundationX/documentation/FoundationX/RecoverableError":{"type":"topic","abstract":[{"type":"text","text":"Describes an error that may be recoverable by presenting several"},{"text":" ","type":"text"},{"type":"text","text":"potential recovery options to the user."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RecoverableError"}],"title":"RecoverableError","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RecoverableError"}],"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError","url":"\/documentation\/foundationx\/recoverableerror"},"doc://com.swallow.documentation.FoundationX/s8SendableP":{"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.swallow.documentation.FoundationX/documentation/FoundationX/RecoverableError/attemptRecovery(optionIndex:)":{"type":"topic","abstract":[{"text":"Attempt to recover from this error when the user selected the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"option at the given index. Returns true to indicate"},{"text":" ","type":"text"},{"type":"text","text":"successful recovery, and false otherwise."}],"required":true,"role":"symbol","title":"attemptRecovery(optionIndex:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"attemptRecovery","kind":"identifier"},{"kind":"text","text":"("},{"text":"optionIndex","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/attemptRecovery(optionIndex:)","url":"\/documentation\/foundationx\/recoverableerror\/attemptrecovery(optionindex:)"},"doc://com.swallow.documentation.FoundationX/documentation/FoundationX":{"abstract":[],"kind":"symbol","title":"FoundationX","identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX","url":"\/documentation\/foundationx","role":"collection","type":"topic"},"doc://com.swallow.documentation.FoundationX/documentation/FoundationX/RecoverableError/recoveryOptions":{"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/recoveryOptions","type":"topic","abstract":[{"text":"Provides a set of possible recovery options to present to the user.","type":"text"}],"url":"\/documentation\/foundationx\/recoverableerror\/recoveryoptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoveryOptions"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"title":"recoveryOptions","role":"symbol","kind":"symbol","required":true},"doc://com.swallow.documentation.FoundationX/documentation/FoundationX/RecoverableError/attemptRecovery(optionIndex:resultHandler:)-5rlzq":{"defaultImplementations":1,"type":"topic","abstract":[{"text":"Attempt to recover from this error when the user selected the","type":"text"},{"type":"text","text":" "},{"text":"option at the given index. This routine must call handler and","type":"text"},{"type":"text","text":" "},{"text":"indicate whether recovery was successful (or not).","type":"text"}],"required":true,"role":"symbol","title":"attemptRecovery(optionIndex:resultHandler:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attemptRecovery"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"optionIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"resultHandler"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/attemptRecovery(optionIndex:resultHandler:)-5rlzq","url":"\/documentation\/foundationx\/recoverableerror\/attemptrecovery(optionindex:resulthandler:)-5rlzq"},"doc://com.swallow.documentation.FoundationX/s5ErrorP":{"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/s5ErrorP","type":"unresolvable","title":"Swift.Error"}}}