{"kind":"symbol","abstract":[{"text":"Attempt to recover from this error when the user selected the","type":"text"},{"type":"text","text":" "},{"text":"option at the given index. Returns true to indicate","type":"text"},{"type":"text","text":" "},{"text":"successful recovery, and false otherwise.","type":"text"}],"sections":[],"metadata":{"required":true,"role":"symbol","platforms":[{"introducedAt":"8.0","name":"iOS","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","introducedAt":"10.10","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"2.0"}],"externalID":"s:10Foundation16RecoverableErrorP15attemptRecovery11optionIndexSbSi_tF","modules":[{"name":"FoundationX"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attemptRecovery"},{"kind":"text","text":"("},{"kind":"externalParam","text":"optionIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","symbolKind":"method","title":"attemptRecovery(optionIndex:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX","doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attemptRecovery","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"optionIndex"},{"kind":"text","text":" "},{"text":"recoveryOptionIndex","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"text":"This entry point is used for recovery of errors handled at","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the “application” granularity, where nothing else in the"},{"type":"text","text":" "},{"type":"text","text":"application can proceed until the attempted error recovery"},{"text":" ","type":"text"},{"type":"text","text":"completes."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/attemptRecovery(optionIndex:)"},"variants":[{"paths":["\/documentation\/foundationx\/recoverableerror\/attemptrecovery(optionindex:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.swallow.documentation.FoundationX/documentation/FoundationX":{"abstract":[],"kind":"symbol","title":"FoundationX","identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX","url":"\/documentation\/foundationx","role":"collection","type":"topic"},"doc://com.swallow.documentation.FoundationX/documentation/FoundationX/RecoverableError/attemptRecovery(optionIndex:)":{"type":"topic","abstract":[{"text":"Attempt to recover from this error when the user selected the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"option at the given index. Returns true to indicate"},{"text":" ","type":"text"},{"type":"text","text":"successful recovery, and false otherwise."}],"required":true,"role":"symbol","title":"attemptRecovery(optionIndex:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"attemptRecovery","kind":"identifier"},{"kind":"text","text":"("},{"text":"optionIndex","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError\/attemptRecovery(optionIndex:)","url":"\/documentation\/foundationx\/recoverableerror\/attemptrecovery(optionindex:)"},"doc://com.swallow.documentation.FoundationX/documentation/FoundationX/RecoverableError":{"type":"topic","abstract":[{"type":"text","text":"Describes an error that may be recoverable by presenting several"},{"text":" ","type":"text"},{"type":"text","text":"potential recovery options to the user."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RecoverableError"}],"title":"RecoverableError","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RecoverableError"}],"identifier":"doc:\/\/com.swallow.documentation.FoundationX\/documentation\/FoundationX\/RecoverableError","url":"\/documentation\/foundationx\/recoverableerror"}}}