{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"consuming","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapError"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"NewFailure"},{"kind":"text","text":">("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"transform","kind":"internalParam"},{"text":": (","kind":"text"},{"text":"Failure","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"NewFailure"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute\/Result","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"text":"Success","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"NewFailure","kind":"typeIdentifier"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"text":" ","kind":"text"},{"text":"NewFailure","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute\/Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"}],"platforms":["macOS"]}],"kind":"declarations"},{"parameters":[{"name":"transform","content":[{"inlineContent":[{"type":"text","text":"A closure that takes the failure value of the"},{"type":"text","text":" "},{"text":"instance.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"Result"},{"text":" instance with the result of evaluating ","type":"text"},{"type":"codeVoice","code":"transform"},{"text":" ","type":"text"},{"text":"as the new failure value if this instance represents a failure.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Use this method when you need to transform the value of a "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" "},{"type":"text","text":"instance when it represents a failure. The following example transforms"},{"type":"text","text":" "},{"type":"text","text":"the error value of a result by wrapping it in a custom "},{"type":"codeVoice","code":"Error"},{"type":"text","text":" type:"}]},{"code":["struct DatedError: Error {","    var error: Error","    var date: Date","","    init(_ error: Error) {","        self.error = error","        self.date = Date()","    }","}","","let result: Result<Int, Error> = \/\/ ...","\/\/ result == .failure(<error value>)","let resultWithDatedError = result.mapError { DatedError($0) }","\/\/ result == .failure(DatedError(error: <error value>, date: <date>))"],"syntax":null,"type":"codeListing"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/compute\/result\/maperror(_:)"]}],"abstract":[{"type":"text","text":"Returns a new result, mapping any failure value using the given"},{"type":"text","text":" "},{"type":"text","text":"transformation."}],"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute","doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute\/Result"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapError","kind":"identifier"},{"text":"<","kind":"text"},{"text":"NewFailure","kind":"genericParameter"},{"text":">((","kind":"text"},{"kind":"typeIdentifier","text":"Failure"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"NewFailure"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"text":"<","kind":"text"},{"text":"Success","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NewFailure"},{"text":">","kind":"text"}],"externalID":"s:s6ResultOsRi_zrlE8mapErroryAByxqd__Gqd__q_XEs0C0Rd__lF","extendedModule":"Swift","title":"mapError(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","conformance":{"constraints":[{"type":"codeVoice","code":"Failure"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Error"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"modules":[{"name":"Compute","relatedModules":["Swift"]}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute\/Result\/mapError(_:)"},"references":{"doc://com.swallow.documentation.Compute/documentation/Compute/Result":{"identifier":"doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute\/Result","kind":"symbol","abstract":[{"type":"text","text":"A value that represents either a success or a failure, including an"},{"type":"text","text":" "},{"type":"text","text":"associated value in each case."}],"role":"symbol","title":"Result","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Result","kind":"identifier"}],"navigatorTitle":[{"text":"Result","kind":"identifier"}],"url":"\/documentation\/compute\/result","type":"topic"},"doc://com.swallow.documentation.Compute/documentation/Compute":{"identifier":"doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute","url":"\/documentation\/compute","role":"collection","kind":"symbol","abstract":[],"type":"topic","title":"Compute"},"doc://com.swallow.documentation.Compute/documentation/Compute/Result/mapError(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Returns a new result, mapping any failure value using the given"},{"text":" ","type":"text"},{"text":"transformation.","type":"text"}],"url":"\/documentation\/compute\/result\/maperror(_:)","conformance":{"constraints":[{"code":"Failure","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Error","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"role":"symbol","type":"topic","title":"mapError(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mapError","kind":"identifier"},{"text":"<","kind":"text"},{"text":"NewFailure","kind":"genericParameter"},{"text":">((","kind":"text"},{"kind":"typeIdentifier","text":"Failure"},{"text":") -> ","kind":"text"},{"text":"NewFailure","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Success","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"NewFailure","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute\/Result\/mapError(_:)"},"doc://com.swallow.documentation.Compute/documentation/Compute/Error":{"url":"\/documentation\/compute\/error","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/com.swallow.documentation.Compute\/documentation\/Compute\/Error","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A type representing an error value that can be thrown."}],"kind":"symbol","title":"Error"}}}