{"metadata":{"roleHeading":"Function","symbolKind":"func","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"XCTFail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"s:7Swallow7XCTFailyySSF","title":"XCTFail(_:)","role":"symbol","modules":[{"name":"CoreModel"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"XCTFail"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = \"\")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"text":"An optional description of the assertion, for inclusion in test","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"results."}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Dynamically creates and records an "},{"type":"codeVoice","code":"XCTIssue"},{"type":"text","text":" under the hood that captures the source code"},{"type":"text","text":" "},{"text":"context of the caller. Useful for defining assertion helpers that fail in indirect code","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"paths, where the "},{"code":"file","type":"codeVoice"},{"type":"text","text":" and "},{"code":"line","type":"codeVoice"},{"text":" of the failure have not been realized.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"This function generates a failure immediately and unconditionally."}],"hierarchy":{"paths":[["doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel\/XCTFail(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/coremodel\/xctfail(_:)"]}],"references":{"doc://com.swallow.documentation.CoreModel/documentation/CoreModel/XCTFail(_:)":{"identifier":"doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel\/XCTFail(_:)","url":"\/documentation\/coremodel\/xctfail(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"XCTFail","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"XCTFail(_:)","role":"symbol","abstract":[{"type":"text","text":"This function generates a failure immediately and unconditionally."}],"type":"topic","kind":"symbol"},"doc://com.swallow.documentation.CoreModel/documentation/CoreModel":{"kind":"symbol","identifier":"doc:\/\/com.swallow.documentation.CoreModel\/documentation\/CoreModel","role":"collection","url":"\/documentation\/coremodel","abstract":[],"type":"topic","title":"CoreModel"}}}